file_format: "1"
id: ergodash
name: ERGODASH
type: shield
url: https://github.com/Namgugn/zmk-ergodash-20250601
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - ergodash_left
  - ergodash_right